### PR TITLE
Fix link to build status

### PR DESCRIPTION
**Pull request by tasuk**
You'll need to activate the repository at: https://travis-ci.org/profile/derekwyatt

### CODE REVIEW

**Comment by ches** [comment]
I'm not sure if the test suite has really been maintained, but will leave this to @derekwyatt since it'll need his action on the Travis side anyhow.

**Comment by tasuk** [comment]
If it hasn't been maintained the Travis link should be removed. No point linking to someone else's build results!

**Comment by derekwyatt** [comment]
I never added this to begin with.  Looked cute, but it's really just silly, so I'll delete it :)

**Comment by derekwyatt** [comment]
Done in sha 7dff00088bde224124f6f03235f06c565372623c

**Comment by tasuk** [comment]
Why is it silly? A working test suite does provide some value, doesn't it?

**Comment by derekwyatt** [comment]
'silly' wasn't the right word. The tests are there and that's good, but they're not critical. We can easily run them by hand rather than maintaining the travis link. I find the automated nature of it to be more problematic than it's worth.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         From: Vít BrunnerSent: Thursday, January 14, 2016 8:15 AMTo: derekwyatt/vim-scalaReply To: derekwyatt/vim-scalaCc: Derek WyattSubject: Re: [vim-scala] Fix link to build status (#118)Why is it silly? A working test suite does provide some value, doesn't it?

—Reply to this email directly or view it on GitHub.

**Pull request closed without merging**
