### PR TITLE
Make comments foldable

### PR DESCRIPTION
**Pull request by normenmueller**
Just a minor improvement suggestion.

### CODE REVIEW

**Comment by ches** [comment]
I'm cool with this, seems a pretty common convention in some other language syntaxes. @derekwyatt?

**Comment by derekwyatt** [comment]
Yeah, looks good @ches and @normenmueller.  Go for it (and thanks for the PR).

**Comment by normenmueller** [comment]
Cool! @ches are you going to merge?

**Comment by ches** [comment]
Done, thanks @normenmueller!

**Pull request merged**
